spring:
  application:
    name: momogum

  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/momogum
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  oauth2:
    kakao:
      client-id: "832eb815f100be4eb52994b0be137716" # 카카오 REST API 키
      redirect-uri: "http://localhost:8080/auth/callback/kakao" # 리디렉션 URI
      token-uri: "https://kauth.kakao.com/oauth/token" # 토큰 발급 URI
      user-info-uri: "https://kapi.kakao.com/v2/user/me" # 사용자 정보 요청 URI

  logging:
    level:
      root: INFO
      org.springframework.security.oauth2.client: DEBUG
      org.springframework.web: DEBUG